interface Env {
  APP_ENV?: string
  DATA_ENV?: string
  FIREBASE_PROJECT_ID?: string
  FIREBASE_AUTH_EMULATOR?: string
  FIREBASE_AUTH_EMULATOR_RESET_MODE?: string
  FIREBASE_WEB_API_KEY?: string
  FIREBASE_ADMIN_SERVICE_ACCOUNT_JSON?: string
  INITIAL_SETUP_KEY?: string
  CORS_ORIGIN?: string
}
